### ISSUE TITLE
Add a parameter for the size of th wells in *_map and *_grid functions

### ISSUE THREAD

**Issue by matushiq** [Swarchal/platetools#14]
It would be nice and helpful to be able to adjust the size of the wells in the final figure.

**Comment by Swarchal** [comment]
Sounds a good idea, should be fairly easy to add this as an optional parameter

**Comment by Swarchal** [comment]
I've exposed the `size` and  `shape` arguments in `geom_point`, so you should be able to use these in most of the *_map and *_grid functions (apart from the median smoothed ones, but I'll sort fix those shortly).

You should be able to use these if you install from github.

example:

```R
library(platetools)

df = data.frame(vals=rnorm(96), wells=num_to_well(1:96))
raw_map(data=df$vals, well=df$wells, size=15, shape=22)
```
![plot1](https://user-images.githubusercontent.com/10051679/49512922-4c596300-f887-11e8-8112-a2c4441dfd4b.png)

```R
df = data.frame(vals=rnorm(96), wells=num_to_well(1:96))
raw_map(data=df$vals, well=df$wells, size=8, shape=21)
```
![plot2](https://user-images.githubusercontent.com/10051679/49513021-95a9b280-f887-11e8-8744-2d53f8c1238f.png)
