### ISSUE TITLE
Nonstandard LICENSE File

### ISSUE THREAD

**Issue by gwaybio** [Swarchal/platetools#20]
Hi @Swarchal - Thanks for putting this package together! I am currently in the process of adding to conda-forge (see conda-forge/staged-recipes#8309). I was wondering if you could clarify the LICENSE file.

the current LICENSE is not MIT - https://opensource.org/licenses/MIT

**Comment by Swarchal** [comment]
Hi thanks for this.

I've replied [here](https://github.com/conda-forge/staged-recipes/pull/8309#discussion_r282185072).

**Comment by gwaybio** [comment]
Awesome! I will close this issue once the feedstock is made 👍
