### ISSUE TITLE
feature_request

### ISSUE THREAD

**Issue by dumont-s** [Swarchal/platetools#4]
Hi, I'm interested to use raw_map but with rainbow colors rather than blue gradient.
Is it possible to do this easily?
Thanks

**Comment by Swarchal** [comment]
Hi, yes you can pass any colour scheme you want via the normal ggplot2 functions.

Quick example using `scale_fill_gradientn()`

```R

library(platetools)
library(ggplot2)

df <- data.frame("well" = num_to_well(1:384, plate=384),
                 "value" = runif(384, 1, 100))

rainbow_colours <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan","#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))


raw_map(df$value, df$well,
        plate = 384) +
    scale_fill_gradientn(colors = rainbow_colours(7))
```

![image](https://user-images.githubusercontent.com/10051679/39011949-d88049f2-440a-11e8-8fd7-ec866e045b92.png)
